-- UC_Light_RwF
-- Author: JNR
--------------------------------------------------------------

-- Policies
--------------------------------------------------------------
UPDATE Policies SET Description='LOC_POLICY_JFD_RATIONAL_BUREAUCRACY_DESCRIPTION_UC_JNR'	WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';
UPDATE Policies SET Description='LOC_POLICY_JFD_FREE_MARKET_DESCRIPTION_UC_JNR'				WHERE PolicyType='POLICY_JFD_FREE_MARKET';
UPDATE Policies SET Description='LOC_POLICY_JFD_CLERIC_OFFICIALS_DESCRIPTION_UC_JNR'		WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';
UPDATE Policies SET Description='LOC_POLICY_JFD_NATIONAL_OPERA_DESCRIPTION_UC_JNR'			WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';
--------------------------------------------------------------

-- Modifiers
--------------------------------------------------------------
INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_RATIONAL_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_RATIONAL_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_RATIONAL_BUREAUCRACY_RESEARCH_LAB_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';



INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_FREE_MARKET_MARKET_GOLD_UC_JNR',						'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_FREE_MARKET_BANK_GOLD_UC_JNR',							'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD_UC_JNR',				'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';



INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_CLERIC_OFFICIALS_SHRINE_FAITH_UC_JNR',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_CLERIC_OFFICIALS_TEMPLE_FAITH_UC_JNR',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_CLERIC_OFFICIALS_' || BuildingType || '_FAITH_UC_JNR',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'
FROM	Buildings WHERE EnabledByReligion=1 
AND		EXISTS (SELECT * FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS');



INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE_UC_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE_UC_JNR',				'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,												ModifierType)
SELECT	'JFD_NATIONAL_OPERA_BROADCAST_CENTER_CULTURE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';
--------------------------------------------------------------

-- ModifierArguments
--------------------------------------------------------------
INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',			'BuildingType',	'BUILDING_LIBRARY'			FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_UNIVERSITY'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_RESEARCH_LAB_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_RESEARCH_LAB'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',			'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_RESEARCH_LAB_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',			'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_RATIONAL_BUREAUCRACY_RESEARCH_LAB_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_MARKET_GOLD_UC_JNR',						'BuildingType',	'BUILDING_MARKET'			FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_BANK_GOLD_UC_JNR',							'BuildingType',	'BUILDING_BANK'				FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD_UC_JNR',				'BuildingType',	'BUILDING_STOCK_EXCHANGE'	FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_MARKET_GOLD_UC_JNR',						'YieldType',	'YIELD_GOLD'				FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_BANK_GOLD_UC_JNR',							'YieldType',	'YIELD_GOLD'				FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD_UC_JNR',				'YieldType',	'YIELD_GOLD'				FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_MARKET_GOLD_UC_JNR',						'Amount',		2							FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_BANK_GOLD_UC_JNR',							'Amount',		2							FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD_UC_JNR',				'Amount',		2							FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_SHRINE_FAITH_UC_JNR',					'BuildingType',	'BUILDING_SHRINE'			FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_TEMPLE_FAITH_UC_JNR',					'BuildingType',	'BUILDING_TEMPLE'			FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_' || BuildingType || '_FAITH_UC_JNR',	'BuildingType',	BuildingType
FROM	Buildings WHERE EnabledByReligion=1 
AND		EXISTS (SELECT * FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS');

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_SHRINE_FAITH_UC_JNR',					'YieldType',	'YIELD_FAITH'				FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_TEMPLE_FAITH_UC_JNR',					'YieldType',	'YIELD_FAITH'				FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_' || BuildingType || '_FAITH_UC_JNR',	'YieldType',	'YIELD_FAITH'
FROM	Buildings WHERE EnabledByReligion=1 
AND		EXISTS (SELECT * FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS');

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_SHRINE_FAITH_UC_JNR',					'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_TEMPLE_FAITH_UC_JNR',					'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_CLERIC_OFFICIALS_' || BuildingType || '_FAITH_UC_JNR',	'Amount',		1
FROM	Buildings WHERE EnabledByReligion=1 
AND		EXISTS (SELECT * FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS');

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE_UC_JNR',			'BuildingType',	'BUILDING_AMPHITHEATER'		FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE_UC_JNR',				'BuildingType',	'BUILDING_MUSEUM_ART'		FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE_UC_JNR',		'BuildingType',	'BUILDING_MUSEUM_ARTIFACT'	FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_BROADCAST_CENTER_CULTURE_UC_JNR',		'BuildingType',	'BUILDING_BROADCAST_CENTER'	FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE_UC_JNR',			'YieldType',	'YIELD_CULTURE'				FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE_UC_JNR',				'YieldType',	'YIELD_CULTURE'				FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE_UC_JNR',		'YieldType',	'YIELD_CULTURE'				FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_BROADCAST_CENTER_CULTURE_UC_JNR',		'YieldType',	'YIELD_CULTURE'				FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE_UC_JNR',			'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE_UC_JNR',				'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,												Name,			Value)
SELECT	'JFD_NATIONAL_OPERA_BROADCAST_CENTER_CULTURE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';
--------------------------------------------------------------

-- PolicyModifiers
--------------------------------------------------------------
INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_RATIONAL_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_RATIONAL_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_RATIONAL_BUREAUCRACY_RESEARCH_LAB_SCIENCE_UC_JNR'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_FREE_MARKET_MARKET_GOLD_UC_JNR'					FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_FREE_MARKET_BANK_GOLD_UC_JNR'						FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD_UC_JNR'			FROM Policies WHERE PolicyType='POLICY_JFD_FREE_MARKET';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_CLERIC_OFFICIALS_SHRINE_FAITH_UC_JNR'				FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_CLERIC_OFFICIALS_TEMPLE_FAITH_UC_JNR'				FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	'POLICY_JFD_CLERIC_OFFICIALS',		'JFD_CLERIC_OFFICIALS_' || BuildingType || '_FAITH_UC_JNR'
FROM	Buildings WHERE EnabledByReligion=1 
AND		EXISTS (SELECT * FROM Policies WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS');

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE_UC_JNR'			FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_NATIONAL_OPERA_BROADCAST_CENTER_CULTURE_UC_JNR'	FROM Policies WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY'	AND ModifierId='JFD_BUREAUCRACY_LIBRARY_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY'	AND ModifierId='JFD_BUREAUCRACY_UNIVERSITY_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY'	AND ModifierId='JFD_BUREAUCRACY_RESEARCH_LAB_SCIENCE';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_FREE_MARKET'			AND ModifierId='JFD_FREE_MARKET_MARKET_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_FREE_MARKET'			AND ModifierId='JFD_FREE_MARKET_BANK_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_FREE_MARKET'			AND ModifierId='JFD_FREE_MARKET_STOCK_EXCHANGE_GOLD';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS'		AND ModifierId='JFD_CLERIC_OFFICIALS_SHRINE_FAITH';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS'		AND ModifierId='JFD_CLERIC_OFFICIALS_TEMPLE_FAITH';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_CLERIC_OFFICIALS'		AND ModifierId='JFD_CLERIC_OFFICIALS_' || (SELECT BuildingType FROM Buildings WHERE EnabledByReligion=1) || '_FAITH';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA'		AND ModifierId='JFD_NATIONAL_OPERA_AMPHITHEATER_CULTURE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA'		AND ModifierId='JFD_NATIONAL_OPERA_MUSEUM_ART_CULTURE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA'		AND ModifierId='JFD_NATIONAL_OPERA_MUSEUM_ARTIFACT_CULTURE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_NATIONAL_OPERA'		AND ModifierId='JFD_NATIONAL_OPERA_BROADCAST_CULTURE';
--------------------------------------------------------------