-- UC_COM_RwF
-- Author: JNR
--------------------------------------------------------------

-- Policies
--------------------------------------------------------------
UPDATE Policies SET Description='LOC_POLICY_JFD_SCHOLASTIC_METHOD_DESCRIPTION_UC_JNR'		WHERE PolicyType='POLICY_JFD_SCHOLASTIC_METHOD';
UPDATE Policies SET Description='LOC_POLICY_JFD_SCIENCE_ACADEMIES_DESCRIPTION_UC_JNR'		WHERE PolicyType='POLICY_JFD_SCIENCE_ACADEMIES';
UPDATE Policies SET Description='LOC_POLICY_JFD_RATIONAL_BUREAUCRACY_DESCRIPTION_UC_JNR'	WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';
--------------------------------------------------------------

-- Modifiers
--------------------------------------------------------------
INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_ACADEMY_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_SCHOOL_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_LABORATORY_SCIENCE_UC_JNR',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_LIBERAL_ARTS_SCIENCE_UC_JNR',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_INSTITUTE_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO Modifiers
		(ModifierId,									ModifierType)
SELECT	'JFD_BUREAUCRACY_EDUCATION_SCIENCE_UC_JNR',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';
--------------------------------------------------------------

-- ModifierArguments
--------------------------------------------------------------
INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_LIBRARY'			FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_ACADEMY_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_JNR_ACADEMY'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',	'BuildingType',	'BUILDING_UNIVERSITY'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_SCHOOL_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_JNR_SCHOOL'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LABORATORY_SCIENCE_UC_JNR',	'BuildingType',	'BUILDING_JNR_LABORATORY'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBERAL_ARTS_SCIENCE_UC_JNR',	'BuildingType',	'BUILDING_JNR_LIBERAL_ARTS'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_INSTITUTE_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_RESEARCH_LAB'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_EDUCATION_SCIENCE_UC_JNR',		'BuildingType',	'BUILDING_JNR_EDUCATION'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_ACADEMY_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',	'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_SCHOOL_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LABORATORY_SCIENCE_UC_JNR',	'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBERAL_ARTS_SCIENCE_UC_JNR',	'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_INSTITUTE_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_EDUCATION_SCIENCE_UC_JNR',		'YieldType',	'YIELD_SCIENCE'				FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_ACADEMY_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR',	'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_SCHOOL_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LABORATORY_SCIENCE_UC_JNR',	'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_LIBERAL_ARTS_SCIENCE_UC_JNR',	'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_INSTITUTE_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO ModifierArguments
		(ModifierId,									Name,			Value)
SELECT	'JFD_BUREAUCRACY_EDUCATION_SCIENCE_UC_JNR',		'Amount',		1							FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

UPDATE ModifierArguments SET Value=25 WHERE ModifierId='JFD_SCHOLASTIC_METHOD_CAMPUS_ADJACENCY'	AND Name='Amount';
UPDATE ModifierArguments SET Value=25 WHERE ModifierId='JFD_SCIENCE_ACADEMIES_CAMPUS_ADJACENCY'	AND Name='Amount';
--------------------------------------------------------------

-- PolicyModifiers
--------------------------------------------------------------
INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'NATURALPHILOSOPHY_NOUNIVERSITYSCIENCE_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_SCHOLASTIC_METHOD';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'FIVEYEARPLAN_NOUNIVERSITYSCIENCE_JNR'			FROM Policies WHERE PolicyType='POLICY_JFD_SCIENCE_ACADEMIES';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_LIBRARY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_ACADEMY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_UNIVERSITY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_SCHOOL_SCIENCE_UC_JNR'			FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_LABORATORY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_LIBERAL_ARTS_SCIENCE_UC_JNR'	FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_INSTITUTE_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_EDUCATION_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

INSERT OR IGNORE INTO PolicyModifiers
		(PolicyType,	ModifierId)
SELECT	PolicyType,		'JFD_BUREAUCRACY_LIBRARYING_AGENCY_SCIENCE_UC_JNR'		FROM Policies WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY' AND ModifierId='JFD_BUREAUCRACY_LIBRARY_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY' AND ModifierId='JFD_BUREAUCRACY_UNIVERSITY_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_JFD_RATIONAL_BUREAUCRACY' AND ModifierId='JFD_BUREAUCRACY_RESEARCH_LAB_SCIENCE';
--------------------------------------------------------------