-- UC_COM_Redux_Delete
-- Author: JNR
--------------------------------------------------------------

UPDATE Buildings SET RegionalRange=0 WHERE BuildingType='BUILDING_STOCK_EXCHANGE';

DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_BANK'			AND ModifierId='JNR_BANK_GOLD_POPULATION_REDUX';
DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_GRAND_BAZAAR'	AND ModifierId='JNR_BANK_GOLD_POPULATION_REDUX';
DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_STOCK_EXCHANGE'	AND ModifierId='JNR_STOCK_EXCHANGE_GOLD_MODIFIER_REDUX';
DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_STOCK_EXCHANGE'	AND ModifierId='JNR_STOCK_EXCHANGE_GOLD_MODIFIER_POWERED_REDUX';
DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_SEAPORT'			AND ModifierId='JNR_BUILDING_SEAPORT_PROMOTION_REDUX';
DELETE FROM BuildingModifiers WHERE BuildingType='BUILDING_HANGAR'			AND ModifierId='JNR_BUILDING_HANGAR_PROMOTION_REDUX';