-- UC_COM_Icons
-- Author: JNR
--------------------------------------------------------------

-- IconTextureAtlases
--------------------------------------------------------------
INSERT OR IGNORE INTO IconTextureAtlases
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES	('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		32,			2,				2,				'UC_COM_Buildings32.dds'),
		('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		38,			2,				2,				'UC_COM_Buildings38.dds'),
		('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		50,			2,				2,				'UC_COM_Buildings50.dds'),
		('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		80,			2,				2,				'UC_COM_Buildings80.dds'),
		('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		128,		2,				2,				'UC_COM_Buildings128.dds'),
		('ICON_ATLAS_JNR_UC_COM_BUILDINGS',		256,		2,				2,				'UC_COM_Buildings256.dds');
--------------------------------------------------------------

-- IconDefinitions
--------------------------------------------------------------
INSERT OR REPLACE INTO IconDefinitions
		(Name,											Atlas,								'Index')
VALUES	('ICON_BUILDING_JNR_MINT',						'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	0),
		('ICON_BUILDING_JNR_WAYSTATION',				'ICON_ATLAS_BUILDINGS',				11),
		('ICON_BUILDING_JNR_GUILDHALL',					'ICON_ATLAS_BUILDINGS',				23),
		('ICON_BUILDING_JNR_MERCHANT_QUARTER',			'ICON_ATLAS_BUILDINGS',				23),
		('ICON_BUILDING_JNR_COMMODITY_EXCHANGE',		'ICON_ATLAS_BUILDINGS',				28),
		('ICON_BUILDING_JNR_MARKETING_AGENCY',			'ICON_ATLAS_BUILDINGS',				28),
		('ICON_BUILDING_JNR_WHARF_BASE',				'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	2),
		('ICON_BUILDING_JNR_WHARF_FISHING',				'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	2),
		('ICON_BUILDING_JNR_WHARF_TRADE',				'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	2),
		('ICON_BUILDING_JNR_LIGHTHOUSE_TRADE',			'ICON_ATLAS_BUILDINGS',				10),
		('ICON_BUILDING_JNR_HAVEN',						'ICON_ATLAS_BUILDINGS',				22),
		('ICON_BUILDING_JNR_CONSULATE',					'ICON_ATLAS_BUILDINGS',				22),
		('ICON_BUILDING_JNR_CRUISE_TERMINAL',			'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	1),
		('ICON_DISTRICT_AERODROME',						'ICON_ATLAS_JNR_UC_COM_BUILDINGS',	3),

		('ICON_BUILDING_JNR_MINT_FOW',					'ICON_ATLAS_BUILDINGS_FOW',	11),
		('ICON_BUILDING_JNR_WAYSTATION_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	11),
		('ICON_BUILDING_JNR_GUILDHALL_FOW',				'ICON_ATLAS_BUILDINGS_FOW',	23),
		('ICON_BUILDING_JNR_MERCHANT_QUARTER_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	23),
		('ICON_BUILDING_JNR_COMMODITY_EXCHANGE_FOW',	'ICON_ATLAS_BUILDINGS_FOW',	28),
		('ICON_BUILDING_JNR_MARKETING_AGENCY_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	28),
		('ICON_BUILDING_JNR_WHARF_BASE_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_WHARF_FISHING_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_WHARF_TRADE_FOW',			'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_LIGHTHOUSE_TRADE_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	10),
		('ICON_BUILDING_JNR_HAVEN_FOW',					'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_CONSULATE_FOW',				'ICON_ATLAS_BUILDINGS_FOW',	22),
		('ICON_BUILDING_JNR_CRUISE_TERMINAL_FOW',		'ICON_ATLAS_BUILDINGS_FOW',	33);
--------------------------------------------------------------