-- UC_Light_Text
-- Author: JNR
--------------------------------------------------------------

-- BaseGameText
--------------------------------------------------------------
INSERT OR IGNORE INTO BaseGameText
		(Tag,																Text)
VALUES	('LOC_BUILDING_HANGAR_DESCRIPTION_UC_JNR_LIGHT',					'+50% combat experience for air units trained in this city.[NEWLINE]All air units trained in this city start with a free promotion.[NEWLINE]+2 air unit slot in Aerodrome district.'),
		('LOC_BUILDING_AIRPORT_DESCRIPTION_UC_JNR_LIGHT',					'+1 [ICON_TradeRoute] Trade Route capacity.[NEWLINE]+25% [ICON_Tourism] Tourism pressure from this city towards other civilizations in the Modern era.[NEWLINE][NEWLINE]+1 air unit slot in Aerodrome district.[NEWLINE]Allows the ability to airlift land units between Aerodrome districts with Airports after the Rapid Deployment civic is unlocked.'),
		('LOC_BUILDING_LIBRARY_DESCRIPTION_UC_JNR_LIGHT',					'+1 additional [ICON_Science] Science for each era since constructed or last repaired.'),
		('LOC_BUILDING_UNIVERSITY_DESCRIPTION_UC_JNR_LIGHT',				'+0.2 [ICON_Science] Science per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR_LIGHT',					'A building unique to Arabia.[NEWLINE]Bonus [ICON_Faith] Faith equal to the adjacency bonus of the Campus district.[NEWLINE][NEWLINE]+0.2 [ICON_Science] Science per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_RESEARCH_LAB_DESCRIPTION_UC_JNR_LIGHT',				'Its base [ICON_Science] Science bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Research Lab building.[NEWLINE]+5% [ICON_Science] Science in this city. Another +5% if the city is powered.'),
		('LOC_BUILDING_BANK_DESCRIPTION_UC_JNR_LIGHT',						'+0.4 [ICON_Gold] Gold per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION_UC_JNR_LIGHT',				'A building unique to the Ottomans.[NEWLINE]Accumulate 1 extra Strategic resource for every different type of Strategic resource this city has improved.[NEWLINE]Receive 1 [ICON_AMENITIES] Amenity for every Luxury resource this city has improved.[NEWLINE][NEWLINE]+0.3 [ICON_Gold] Gold per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_STOCK_EXCHANGE_DESCRIPTION_UC_JNR_LIGHT',			'Its base [ICON_Gold] Gold bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Stock Exchange building.[NEWLINE]+5% [ICON_Gold] Gold in this city. Another +5% if the city is powered.'),
		('LOC_BUILDING_ARMORY_DESCRIPTION_UC_JNR_LIGHT',					'+1 [ICON_Production] Production to all Strategic Resources in this city.[NEWLINE][NEWLINE]+25% combat experience for all land units trained in this city.[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).'),
		('LOC_BUILDING_MILITARY_ACADEMY_DESCRIPTION_UC_JNR_LIGHT',			'+25% combat experience for all land units trained in this city.[NEWLINE]All land units trained in this city start with a free promotion.[NEWLINE]Strategic Resource Stockpiles increased +10 (on Standard Speed).[NEWLINE]Allows Corps and Armies to be trained directly. Corps and Army training costs reduced 25%.'),
		('LOC_BUILDING_ARENA_DESCRIPTION_UC_JNR_LIGHT',						'+1 [ICON_Culture] Culture to all [ICON_RESOURCE_HORSES] Horses in this city.'),
		('LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR_LIGHT',					'A building unique to the Aztecs.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture to all Quarries in this city.'),
		('LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_UC_JNR_LIGHT',				'+1 [ICON_GOLD] Gold to all tiles with Breathtaking Appeal in this city.'),
		('LOC_BUILDING_SEAPORT_DESCRIPTION_UC_JNR_LIGHT',					'+2 [ICON_GOLD] Gold on all Coast tiles for this city.[NEWLINE][NEWLINE]+25% combat experience for all naval units trained in this city.[NEWLINE]All naval units trained in this city start with a free promotion.[NEWLINE]Allows Fleets and Armadas to be trained directly.[NEWLINE]Fleet and Armada training costs reduced 25%. '),
		('LOC_BUILDING_WORKSHOP_DESCRIPTION_UC_JNR_LIGHT',					'+0.2 [ICON_Production] Production per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_ELECTRONICS_FACTORY_DESCRIPTION_UC_JNR_LIGHT',		'A building unique to Japan.[NEWLINE]Provides +4 [ICON_Culture] Culture to this city after researching the Electricity technology.'),
		('LOC_BUILDING_COAL_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',			'Automatically converts any amount of [ICON_RESOURCE_COAL] Coal into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_COAL] Coal [ICON_PowerRight] 4 [ICON_Power] Power[NEWLINE][ICON_Bullet]Heavy CO2 into the atmosphere.[NEWLINE]All tiles in this city -2 Appeal.[NEWLINE][NEWLINE]Its [ICON_Production] Production bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Power Plant building.[NEWLINE]+10% [ICON_Production] Production in this city if the city is powered.'),
		('LOC_BUILDING_FOSSIL_FUEL_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',	'Automatically converts any amount of [ICON_RESOURCE_OIL] Oil into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_OIL] Oil [ICON_PowerRight] 4 [ICON_Power] Power[NEWLINE][ICON_Bullet]Moderate CO2 into the atmosphere.[NEWLINE]All tiles in this city -1 Appeal.[NEWLINE][NEWLINE]Its [ICON_Production] Production bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Power Plant building.[NEWLINE]+10% [ICON_Production] Production in this city if the city is powered.'),
		('LOC_BUILDING_POWER_PLANT_DESCRIPTION_UC_JNR_LIGHT',				'Automatically converts any amount of [ICON_RESOURCE_URANIUM] Uranium into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_URANIUM] Uranium [ICON_PowerRight] 16 [ICON_Power] Power[NEWLINE][ICON_Bullet]Miniscule CO2 into the atmosphere.[NEWLINE][NEWLINE]Once built, as a Nuclear Power Plant ages, there is an increased chance for a Nuclear Accident to occur. Its [ICON_Production] Production and [ICON_Science] Science bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Power Plant building.[NEWLINE]+10% [ICON_Production] Production in this city if the city is powered.'),
		('LOC_BUILDING_TEMPLE_DESCRIPTION_UC_JNR_LIGHT',					'+0.2 [ICON_Faith] Faith per turn for each [ICON_Citizen] Citizen in the city.[NEWLINE][NEWLINE]Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks. These units can only be purchased with [ICON_Faith] Faith.'),
		('LOC_BUILDING_STAVE_CHURCH_DESCRIPTION_UC_JNR_LIGHT',				'A building unique to Norway.[NEWLINE]Holy Site districts get an additional standard adjacency bonus from Woods.[NEWLINE]+1 [ICON_PRODUCTION] Production to each coastal resource tile in this city.[NEWLINE][NEWLINE]+0.2 [ICON_Faith] Faith per turn for each [ICON_Citizen] Citizen in the city.[NEWLINE][NEWLINE]Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks. These units can only be purchased with [ICON_Faith] Faith.'),
		('LOC_BUILDING_PRASAT_DESCRIPTION_UC_JNR_LIGHT',					'A building unique to Khmer. Replaces the Temple.[NEWLINE]Missionaries purchased in this city receive the Martyr ability which grants a [ICON_GreatWork_Relic] Relic if this Missionary dies in Theological Combat.[NEWLINE][NEWLINE]+0.2 [ICON_Faith] Faith per turn for each [ICON_Citizen] Citizen in the city.[NEWLINE][NEWLINE]Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks. These units can only be purchased with [ICON_Faith] Faith.'),
		('LOC_BUILDING_AMPHITHEATER_DESCRIPTION_UC_JNR_LIGHT',				'+0.2 [ICON_Culture] Culture per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_MUSEUM_ART_DESCRIPTION_UC_JNR_LIGHT',				'+1 [ICON_Culture] Culture per [ICON_GOVERNOR] Promotion of a Governor established in this city.[NEWLINE][NEWLINE]Holds [ICON_GreatWork_Landscape] Great Works of Art.'),
		('LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION_UC_JNR_LIGHT',			'+3 [ICON_Culture] Culture to all [ICON_RESOURCE_ANTIQUITY_SITE] Antiquity Sites and [ICON_RESOURCE_SHIPWRECK] Shipwrecks in this city.[NEWLINE][NEWLINE]Holds [ICON_GreatWork_Artifact] Artifacts.'),
		('LOC_BUILDING_BROADCAST_CENTER_DESCRIPTION_UC_JNR_LIGHT',			'Its base [ICON_Culture] Culture bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Broadcast Center building.[NEWLINE]+5% [ICON_Culture] Culture in this city. Another +5% if the city is powered.'),
		('LOC_BUILDING_FILM_STUDIO_DESCRIPTION_UC_JNR_LIGHT',				'A building unique to America.[NEWLINE]+100% [ICON_Tourism] Tourism pressure from this city towards other civilizations in the Modern era.[NEWLINE][NEWLINE]Its base [ICON_Culture] Culture bonus is extended to all City Centers within 6 tiles that do not already have a bonus from a Broadcast Center building.[NEWLINE]+5% [ICON_Culture] Culture in this city. Another +5% if the city is powered.'),
		('LOC_POLICY_RATIONALISM_DESCRIPTION_JNR_UC_LIGHT',					'Extra [ICON_Science] Science from buildings in Campuses: +1 if city [ICON_CITIZEN] population is 10 or higher, +1 if district has at least +3 adjacency bonus.'),
		('LOC_POLICY_FREE_MARKET_DESCRIPTION_JNR_UC_LIGHT',					'Extra [ICON_Gold] Gold from buildings in Commercial Hubs: +2 if city [ICON_CITIZEN] population is 10 or higher, +2 if district has at least +4 adjacency bonus.'),
		('LOC_POLICY_SIMULTANEUM_DESCRIPTION_JNR_UC_LIGHT',					'Extra [ICON_Faith] Faith from buildings in Holy Sites: +1 if city [ICON_CITIZEN] population is 10 or higher, +1 if district has at least +3 adjacency bonus.'),
		('LOC_POLICY_GRAND_OPERA_DESCRIPTION_JNR_UC_LIGHT',					'Extra [ICON_Culture] Culture from buildings in Theater Squares: +1 if city [ICON_CITIZEN] population is 10 or higher, +1 if district has at least +3 adjacency bonus.');
--------------------------------------------------------------

-- CX
-- BaseGameText
--------------------------------------------------------------
INSERT OR IGNORE INTO BaseGameText
		(Tag,																Text)
VALUES	('LOC_BUILDING_MADRASA_DESCRIPTION_UC_JNR_LIGHT_CX',				'A building unique to Arabia. Replaces the University.[NEWLINE]Bonus [ICON_Faith] Faith equal to the adjacency bonus of the Campus district.[NEWLINE]All [ICON_TradeRoute] Trade Routes from this city gain +1 [ICON_Science] Science.[NEWLINE]Domestic [ICON_TradeRoute] Trade Routes from this city gain +1 [ICON_Food] Food. International [ICON_TradeRoute] Trade Routes from this city gain +1 [ICON_Faith] Faith.[NEWLINE][NEWLINE]+0.2 [ICON_Science] Science per turn for each [ICON_Citizen] Citizen in the city.'),
		('LOC_BUILDING_TLACHTLI_DESCRIPTION_UC_JNR_LIGHT_CX',				'A building unique to Aztecs. Replaces the Arena.[NEWLINE]Grants the ability to purchase land units with [ICON_Faith] Faith in this city.[NEWLINE][NEWLINE]+1 [ICON_Culture] Culture to all Quarries in this city.'),
		('LOC_BUILDING_PRASAT_DESCRIPTION_UC_JNR_LIGHT_CX',					'A building unique to Khmer. Replaces the Temple.[NEWLINE]Grants the Holy Site district a Standard [ICON_Faith] Faith adjacency bonus from Marsh and Floodplains.[NEWLINE]Missionaries purchased in this city receive the Martyr ability which grants a [ICON_GreatWork_Relic] Relic if defeated in Theological Combat.[NEWLINE][NEWLINE]+0.2 [ICON_Faith] Faith per turn for each [ICON_Citizen] Citizen in the city.[NEWLINE][NEWLINE]Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks. These units can only be purchased with [ICON_Faith] Faith.');
--------------------------------------------------------------