-- Tier_3_City_State_Bonuses_CIVITAS
-- Author: JNR
--------------------------------------------------------------

-- TraitModifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO TraitModifiers
		(ModifierId,													TraitType)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_UNIQUE_INFLUENCE_BONUS_JNR',		'CVS_MINOR_CIV_AGRICULTURAL_TRAIT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO TraitModifiers
		(ModifierId,													TraitType)
SELECT	'MINOR_CIV_CVS_CONSULAR_UNIQUE_INFLUENCE_BONUS_JNR',			'CVS_MINOR_CIV_AGRICULTURAL_TRAIT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO TraitModifiers
		(ModifierId,													TraitType)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_UNIQUE_INFLUENCE_BONUS_JNR',		'CVS_MINOR_CIV_AGRICULTURAL_TRAIT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO TraitModifiers
		(ModifierId,													TraitType)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_FOOD_JNR',		'CVS_MINOR_CIV_AGRICULTURAL_TRAIT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO TraitModifiers
		(ModifierId,													TraitType)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR',	'CVS_MINOR_CIV_AGRICULTURAL_TRAIT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- Modifiers and ModifierArguments (Attach Modifier System)
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers
		(ModifierId,													ModifierType,							SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_UNIQUE_INFLUENCE_BONUS_JNR',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'JNR_PLAYER_IS_SUZERAIN_OR_HAS_ENORMOUS_INFLUENCE'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,													ModifierType,							SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_CONSULAR_UNIQUE_INFLUENCE_BONUS_JNR',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'JNR_PLAYER_IS_SUZERAIN_OR_HAS_ENORMOUS_INFLUENCE'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,													ModifierType,							SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_UNIQUE_INFLUENCE_BONUS_JNR',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'JNR_PLAYER_IS_SUZERAIN_OR_HAS_ENORMOUS_INFLUENCE'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,													ModifierType,							SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_FOOD_JNR',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'JNR_PLAYER_IS_SUZERAIN_OR_HAS_ENORMOUS_INFLUENCE'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,													ModifierType,							SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'JNR_PLAYER_IS_SUZERAIN_OR_HAS_ENORMOUS_INFLUENCE'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,													Name,			Value)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_UNIQUE_INFLUENCE_BONUS_JNR',		'ModifierId',	'MINOR_CIV_CVS_AGRICULTURAL_YIELD_FOR_SEWER_JNR'				FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,													Name,			Value)
SELECT	'MINOR_CIV_CVS_CONSULAR_UNIQUE_INFLUENCE_BONUS_JNR',			'ModifierId',	'MINOR_CIV_CVS_CONSULAR_LOYALTY_FOR_TIER3_GOVERNMENT_JNR'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,													Name,			Value)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_UNIQUE_INFLUENCE_BONUS_JNR',		'ModifierId',	'MINOR_CIV_CVS_ENTERTAINMENT_YIELD_FOR_TIER3_ENTERTAINMENT_JNR'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,													Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_FOOD_JNR',		'ModifierId',	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_FOOD_JNR'				FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,													Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR',	'ModifierId',	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

UPDATE	ModifierArguments												SET				Value='MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER1_GOVERNMENT_JNR'	WHERE ModifierId='CVS_MINOR_CIV_CONSULAR_MEDIUM_INFLUENCE_BONUS' AND Name='ModifierId';
UPDATE	ModifierArguments												SET				Value='MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER2_GOVERNMENT_JNR'	WHERE ModifierId='CVS_MINOR_CIV_CONSULAR_LARGE_INFLUENCE_BONUS' AND Name='ModifierId';
--------------------------------------------------------------

-- Modifiers
--------------------------------------------------------------
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_YIELD_FOR_SEWER_JNR',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',							NULL														FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER1_GOVERNMENT_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_IDENTITY_PER_TURN',								'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER1'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER2_GOVERNMENT_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_IDENTITY_PER_TURN',								'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER2'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER3_GOVERNMENT_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_IDENTITY_PER_TURN',								'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER3'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_YIELD_FOR_TIER3_ENTERTAINMENT_JNR',	'CVS_MODIFIER_ENTERTAINMENT_PLAYER_CITIES_ADJUST_AMENITIES_FROM_CITY_STATES',	'JNR_CVS_ENTERTAINMENT_CITYSTATE_CITY_HAS_STADIUM'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_FOOD_JNR',				'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',							NULL														FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Modifiers
		(ModifierId,														ModifierType,																	SubjectRequirementSetId)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_PRODUCTION_JNR',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',							NULL														FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- ModifierArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_YIELD_FOR_SEWER_JNR',					'YieldType',	'YIELD_FOOD'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_YIELD_FOR_SEWER_JNR',					'BuildingType',	'BUILDING_SEWER'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_YIELD_FOR_SEWER_JNR',					'Amount',		2					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER1_GOVERNMENT_JNR',			'Amount',		2					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER2_GOVERNMENT_JNR',			'Amount',		2					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_CONSULAR_YIELD_FOR_TIER3_GOVERNMENT_JNR',			'Amount',		2					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_YIELD_FOR_TIER3_ENTERTAINMENT_JNR',	'Amount',		1					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_FOOD_JNR',				'YieldType',	'YIELD_FOOD'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_FOOD_JNR',				'BuildingType',	'BUILDING_SEAPORT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_FOOD_JNR',				'Amount',		1					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_PRODUCTION_JNR',			'YieldType',	'YIELD_PRODUCTION'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_PRODUCTION_JNR',			'BuildingType',	'BUILDING_SEAPORT'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierArguments
		(ModifierId,														Name,			Value)
SELECT	'MINOR_CIV_CVS_MARITIME_YIELD_FOR_SEAPORT_PRODUCTION_JNR',			'Amount',		1					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- RequirementSets
--------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSets
		(RequirementSetId,											RequirementSetType)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER1',	'REQUIREMENTSET_TEST_ANY'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSets
		(RequirementSetId,											RequirementSetType)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER2',	'REQUIREMENTSET_TEST_ANY'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSets
		(RequirementSetId,											RequirementSetType)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER3',	'REQUIREMENTSET_TEST_ANY'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSets
		(RequirementSetId,											RequirementSetType)
SELECT	'JNR_CVS_ENTERTAINMENT_CITYSTATE_CITY_HAS_STADIUM',			'REQUIREMENTSET_TEST_ALL'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- RequirementSetRequirements
--------------------------------------------------------------
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER1',	'JNR_CITY_HAS_GOV_BUILDING_TALL'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER1',	'JNR_CITY_HAS_GOV_BUILDING_WIDE'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER1',	'JNR_CITY_HAS_GOV_BUILDING_CONQUEST'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER2',	'JNR_CITY_HAS_GOV_BUILDING_CITYSTATES'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER2',	'JNR_CITY_HAS_GOV_BUILDING_SPIES'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER2',	'JNR_CITY_HAS_GOV_BUILDING_FAITH'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER3',	'JNR_CITY_HAS_GOV_BUILDING_MILITARY'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER3',	'JNR_CITY_HAS_GOV_BUILDING_CULTURE'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_CONSULAR_CITYSTATE_PLAYER_HAS_GOV_BUILDING_TIER3',	'JNR_CITY_HAS_GOV_BUILDING_SCIENCE'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementSetRequirements
		(RequirementSetId,											RequirementId)
SELECT	'JNR_CVS_ENTERTAINMENT_CITYSTATE_CITY_HAS_STADIUM',			'JNR_CITY_HAS_STADIUM'					FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- Requirements
--------------------------------------------------------------
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_TALL',		'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_WIDE',		'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CONQUEST',	'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CITYSTATES',	'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_SPIES',		'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_FAITH',		'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_MILITARY',	'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CULTURE',	'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_SCIENCE',	'REQUIREMENT_PLAYER_HAS_BUILDING'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO Requirements
		(RequirementId,							RequirementType)
SELECT	'JNR_CITY_HAS_STADIUM',					'REQUIREMENT_CITY_HAS_BUILDING'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- RequirementArguments
--------------------------------------------------------------
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_TALL',		'BuildingType',	'BUILDING_GOV_TALL'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_WIDE',		'BuildingType',	'BUILDING_GOV_WIDE'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CONQUEST',	'BuildingType',	'BUILDING_GOV_CONQUEST'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CITYSTATES',	'BuildingType',	'BUILDING_GOV_CITYSTATES'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_SPIES',		'BuildingType',	'BUILDING_GOV_SPIES'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_FAITH',		'BuildingType',	'BUILDING_GOV_FAITH'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_MILITARY',	'BuildingType',	'BUILDING_GOV_MILITARY'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_CULTURE',	'BuildingType',	'BUILDING_GOV_CULTURE'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_GOV_BUILDING_SCIENCE',	'BuildingType',	'BUILDING_GOV_SCIENCE'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

INSERT OR REPLACE INTO RequirementArguments
		(RequirementId,							Name,			Value)
SELECT	'JNR_CITY_HAS_STADIUM',					'BuildingType',	'BUILDING_STADIUM'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
--------------------------------------------------------------

-- ModifierStrings
--------------------------------------------------------------
INSERT OR REPLACE INTO ModifierStrings
		(ModifierId,													Context,	Text)
SELECT	'MINOR_CIV_CVS_AGRICULTURAL_UNIQUE_INFLUENCE_BONUS_JNR',		'Preview',	'LOC_MINOR_CIV_CVS_AGRICULTURAL_UNIQUE_INFLUENCE_BONUS_JNR'			FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierStrings
		(ModifierId,													Context,	Text)
SELECT	'MINOR_CIV_CVS_CONSULAR_UNIQUE_INFLUENCE_BONUS_JNR',			'Preview',	'LOC_MINOR_CIV_CVS_CONSULAR_UNIQUE_INFLUENCE_BONUS_JNR'				FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierStrings
		(ModifierId,													Context,	Text)
SELECT	'MINOR_CIV_CVS_ENTERTAINMENT_UNIQUE_INFLUENCE_BONUS_JNR',		'Preview',	'LOC_MINOR_CIV_CVS_ENTERTAINMENT_UNIQUE_INFLUENCE_BONUS_JNR'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierStrings
		(ModifierId,													Context,	Text)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_FOOD_JNR',		'Preview',	'LOC_MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_FOOD_JNR'		FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';
INSERT OR REPLACE INTO ModifierStrings
		(ModifierId,													Context,	Text)
SELECT	'MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR',	'Preview',	'LOC_MINOR_CIV_CVS_MARITIME_UNIQUE_INFLUENCE_BONUS_PRODUCTION_JNR'	FROM Leaders WHERE LeaderType='CVS_LEADER_MINOR_CIV_AGRICULTURAL';

UPDATE	ModifierStrings													SET		Text='LOC_CVS_MINOR_CIV_CONSULAR_TRAIT_MEDIUM_INFLUENCE_BONUS_JNR_UC'	WHERE ModifierId='CVS_MINOR_CIV_CONSULAR_MEDIUM_INFLUENCE_BONUS';
UPDATE	ModifierStrings													SET		Text='LOC_CVS_MINOR_CIV_CONSULAR_TRAIT_LARGE_INFLUENCE_BONUS_JNR_UC'	WHERE ModifierId='CVS_MINOR_CIV_CONSULAR_LARGE_INFLUENCE_BONUS';
--------------------------------------------------------------

